alias: Low Battery Level Check
use_blueprint:
  path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
  input:
    actions:
      - service: notify.slack
        data_template:
          title: Battery Level Check
          message: >
            Low battery level for sensors: {{ sensors }}.

