alias: Bed Room Mini Switch
mode: restart
use_blueprint:
  path: SeanM/zha-aqara-wireless-mini-switch.yaml
  input:
    aqara_mini_switch: f16c892cbe1ea75906a419aae6fb11fe
    button_single_press:
      - service: light.toggle
        target:
          entity_id: light.bedroom_closet
        data:
          brightness_pct: 100
          hs_color: [323, 100]
