---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky
  - clickhouse
  - cloudflared
  - dyndns
  # - gitlab # -> not yet
  - hammond
  - home-assistant
  - homer
  - linkding
  - pairdrop
  - paperless
  - plausible
  - unbound
  - unifi
  - vaultwarden
  - vikunja
