---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - silences.yaml
  - kube-prometheus-stack
  - cloudflare-exporter
  - fritzbox-exporter
  - loki
  - magicmirror
  - minio
  - plausible-exporter
  - speedtest-exporter
  - unifi-poller
  - vector
