---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare-exporter
  namespace: flux-system
spec:
  url: https://lablabs.github.io/cloudflare-exporter/
  interval: 10m0s
