---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: deliveryhero
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/deliveryhero/helm-charts
  interval: 10m0s
