---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/falcosecurity/charts
  interval: 10m0s
