---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: giantswarm
  namespace: flux-system
spec:
  url: https://giantswarm.github.io/control-plane-catalog/
  interval: 10m0s
