---
# storage
storage_groups:
  - name: data-vg
    disk: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
    host: host0
storage_volumes:
  - name: data-lv
    group: data-vg
    size: +100%FREE
    type: ext4
    mount: /data

# docker
docker_data_dir: /data/docker
