all_switches:
  name: All Switches
  icon: mdi:toggle-switch
  all: yes
  entities:
    # living room
    - switch.baum
    - switch.lampe

    # kitchen
    - switch.lichterkette

    # childrens room
    - switch.kugel
    - switch.love
all_lights:
  name: All Lights
  icon: mdi:lightbulb-group
  all: yes
  entities:
    # living room
    - light.living_room_tv_leds

    # bedroom
    - light.bedroom_closet

    # office
    - light.office_desk
