apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik.${DOMAIN}
  namespace: traefik
spec:
  secretName: traefik.${DOMAIN}
  dnsNames:
    - traefik.${DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt-production
