---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - system-upgrade
  - cert-manager
  - cloudnative-pg
  - crowdsec
  - trivy-operator
  - node-problem-detector
  - kured
  - traefik
  - traefik-errors
  - velero
