---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # flux
  - flux

  # dependencies
  - overlays/crds.yaml
  - overlays/charts.yaml

  # resources
  - overlays/config.yaml
  - overlays/core.yaml
  - overlays/services.yaml
