---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # dependencies
  - overlays/crds.yaml
  - overlays/charts.yaml

  # resources
  - overlays/config.yaml
  - overlays/core.yaml
  - overlays/services.yaml
