---
# --- hosts
- name: Setup Ryloth
  hosts: ryloth.iske.cloud
  become: true
  roles:
    - role: minio
      tags:
        - minio

- name: Setup ZigBeeProxy
  hosts: zigbeeproxy.iske.cloud
  roles:
    - role: ser2net
      tags:
        - ser2net
