# living room
switch.baum:
  icon: mdi:string-lights
switch.duftlampe:
  icon: mdi:lightbulb
switch.lampe:
  icon: mdi:lightbulb
switch.kugel:
  icon: mdi:string-lights
light.living_room_tv_leds:
  icon: mdi:string-lights

# kitchen
switch.lichterkette:
  icon: mdi:string-lights

# bathroom
sensor.withings_weight_kg_pascal_iske:
  friendly_name: Pascals Weight
sensor.withings_weight_kg_sarah_iske:
  friendly_name: Sarahs Weight

# bedroom
light.bedroom_closet:
  icon: mdi:string-lights

# childrens room
switch.love:
  icon: mdi:string-lights

# office
sensor.canon_mx470_series:
  friendly_name: State
  icon: mdi:flash
sensor.canon_mx470_series_black:
  friendly_name: Black Ink
sensor.canon_mx470_series_color:
  friendly_name: Color Ink

# other
sensor.epson_et_2750_series:
  friendly_name: State
  icon: mdi:flash
sensor.epson_et_2750_series_black_ink:
  friendly_name: Black Ink
sensor.epson_et_2750_series_cyan_ink:
  friendly_name: Cyan Ink
sensor.epson_et_2750_series_magenta_ink:
  friendly_name: Magenta Ink
sensor.epson_et_2750_series_yellow_ink:
  friendly_name: Yellow Ink
sensor.tankerkoenig_car_tank_24_diesel:
  friendly_name: Neumann Diesel
sensor.tankerkoenig_car_tank_24_e5:
  friendly_name: Neumann E5
sensor.tankerkoenig_shell_rodgau_3_niederroden_frankfurter_str_97_diesel:
  friendly_name: Shell Diesel
sensor.tankerkoenig_shell_rodgau_3_niederroden_frankfurter_str_97_e5:
  friendly_name: Shell E5
sensor.tankerkoenig_tankcenter_rodgau_diesel:
  friendly_name: Tankcenter Diesel
sensor.tankerkoenig_tankcenter_rodgau_e5:
  friendly_name: Tankcenter E5
