cloud:
  alexa:
    filter:
      include_entities:
        # sensors
        - sensor.childrens_room_climate_lumi_temperature
        - sensor.bedroom_climate_lumi_temperature
        - sensor.living_room_climate_lumi_temperature
        - sensor.bathroom_climate_lumi_temperature
        - sensor.kitchen_climate_lumi_temperature
        - sensor.cpu_temperature

        # lights
        - light.bedroom_closet

        # switches
        - switch.baum
        - switch.duftlampe
        - switch.lampe
        - switch.lichterkette
        - switch.love
        - switch.kugel

        # network
        - switch.pi_hole
        - switch.netflix
        - switch.synology_nas
        - switch.vacation_mode
      include_domains:
        - light
        - switch
      exclude_entities:
        - switch.fritz_box_7590_wi_fi_easy_huggie_box
        - switch.fritz_box_7590_wi_fi_easy_huggie_box_5ghz
        - switch.fritz_box_7590_wi_fi_fritz_box_gastzugang
    entity_config:
      # sensors
      sensor.childrens_room_climate_lumi_temperature:
        name: Kinderzimmer Temperatur
        display_categories: TEMPERATURE_SENSOR
      sensor.bedroom_climate_lumi_temperature:
        name: Schlafzimmer Temperatur
        display_categories: TEMPERATURE_SENSOR
      sensor.living_room_climate_lumi_temperature:
        name: Wohnzimmer Temperatur
        display_categories: TEMPERATURE_SENSOR
      sensor.bathroom_climate_lumi_temperature:
        name: Badezimmer Temperatur
        display_categories: TEMPERATURE_SENSOR
      sensor.kitchen_climate_lumi_temperature:
        name: KÃ¼che Temperatur
        display_categories: TEMPERATURE_SENSOR
      sensor.cpu_temperature:
        name: CPU Temperatur
        display_categories: TEMPERATURE_SENSOR

      # lights
      light.bedroom_closet:
        name: Licht
        display_categories: LIGHT
      light.living_room_tv_leds:
        name: LEDs
        display_categories: LIGHT

      # switches
      switch.baum:
        name: Baum
        display_categories: LIGHT
      switch.lampe:
        name: Lampe
        display_categories: LIGHT
      switch.lichterkette:
        name: Lichterkette
        display_categories: LIGHT
      switch.love:
        name: Love
        display_categories: LIGHT
      switch.kugel:
        name: Kugel
        display_categories: LIGHT

      # network
      switch.pi_hole:
        name: Pi-Hole
        display_categories: NETWORK_HARDWARE
      switch.netflix:
        name: Netflix
        display_categories: STREAMING_DEVICE
      switch.synology_nas:
        name: Synology NAS
        display_categories: NETWORK_HARDWARE
