# general settings
homeassistant:
  name: N12
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  unit_system: metric
  time_zone: Europe/Berlin

# enables configuration ui
config:

# incorporate latest changes
default_config:

# modify logger
logger:
  default: warn
  logs:
    homeassistant.setup: warn
    homeassistant.loader: warn
    homeassistant.helpers.entity: warn
    homeassistant.components.http.ban: warn
    homeassistant.components.discovery: warn
    homeassistant.components.upnp: warn
    homeassistant.components.ipp: warn
    homeassistant.components.pi_hole: warn
    pyhap.hap_server: warn
    hole: warn

# database recorder
recorder:
  purge_keep_days: 7
  commit_interval: 600

# enable themes
frontend:
  themes: !include_dir_merge_named ../themes

# enable auto discovery
discovery:
  ignore:
    - frontier_silicon

# enable ios frontend
ios:

# enable wake on lan
wake_on_lan:

# split imports
automation: !include_dir_list ../automations
group: !include_dir_merge_named ../groups
scene: !include_dir_list ../scenes
script: !include_dir_merge_named ../scripts
sensor: !include_dir_list ../sensors
switch: !include_dir_list ../switches
