prometheus:
  namespace: homeassistant
  filter:
    include_entity_globs:
      - sensor.cert_*
      - sensor.fritzbox_*
      - sensor.tankerkoenig_*
      - sensor.withings_weight_*
      - sensor.*_battery_state
      - sensor.*_lumi_power
      - sensor.*_lumi_temperature
      - sensor.*_lumi_humidity
      - sensor.*_lumi_pressure
