title: Home
path: home
icon: mdi:home
theme: Google - Dark
panel: true
badges: []
cards:
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.spotify_pascal_iske
            style: |
              .background .color-block, .background .no-img, .background .image {
                background: inherit;
              }
          - type: weather-forecast
            entity: weather.home
          - type: sensor
            entity: sensor.rodgau_nieder_roden_to_westend_frankfurt_a_m
            name: S1 â†’ Westend
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Weight Pascal
                graph: line
                icon: mdi:scale-bathroom
                hours_to_show: 168
                entity: sensor.withings_weight_kg_pascal_iske_2
              - type: sensor
                name: Weight Sarah
                graph: line
                icon: mdi:scale-bathroom
                hours_to_show: 168
                entity: sensor.withings_weight_kg_sarah_iske_2
      - type: vertical-stack
        cards:
          - type: entities
            title: Entrance
            state_color: false
            show_header_toggle: false
            entities:
              - entity: binary_sensor.entrance_lumi_magnet_on_off
                secondary_info: last-changed
                icon: 'mdi:door'
                name: Door
              - entity: sensor.entrance_lumi_magnet_power
                secondary_info: last-changed
                name: Battery
          - type: entities
            title: Bedroom
            state_color: true
            show_header_toggle: true
            entities:
              - entity: sensor.bed_room_lumi_temperature
                secondary_info: last-changed
                name: Temperature
              - entity: switch.licht
                secondary_info: last-changed
              - entity: switch.love
                secondary_info: last-changed
          - type: entities
            title: Living Room
            state_color: true
            show_header_toggle: true
            entities:
              - entity: switch.kugel
                secondary_info: last-changed
              - entity: switch.lampe
                secondary_info: last-changed
              - entity: switch.duftlampe
                secondary_info: last-changed
          - type: entity-filter
            show_empty: false
            state_filter:
              - operator: '!='
                value: 'unavailable'
            card:
              title: Printer
              icon: mdi:printer
              show_header_toggle: false
            entities:
              - entity: sensor.epson_et_2750_series
              - entity: sensor.epson_et_2750_series_black_ink
              - entity: sensor.epson_et_2750_series_cyan_ink
              - entity: sensor.epson_et_2750_series_magenta_ink
              - entity: sensor.epson_et_2750_series_yellow_ink
