title: Home
path: home
icon: mdi:home
theme: Google - Dark
panel: true
badges: []
cards:
  - type: custom:mod-card
    card:
      type: custom:layout-card
      layout_type: custom:horizontal-layout
      layout:
        max_width: 1000
      cards:
        - type: vertical-stack
          cards:
            - type: custom:swipe-card
              parameters:
                pagination:
                  type: bullets
                mousewheel:
                  forceToAxis: true
                keyboard:
                  enabled: true
                  onlyInViewport: true
              cards:
                - type: media-control
                  entity: media_player.spotify_pascal_iske
                  card_mod:
                    style: |
                      .player, .type-media-control {
                        min-height: 196px;
                      }

                      .background .color-block, .background .no-img, .background .image {
                        background: inherit;
                      }
                - type: media-control
                  entity: media_player.ps4_pi
                  card_mod:
                    style: |
                      .player, .type-media-control {
                        min-height: 196px;
                      }

                      .background .color-block, .background .no-img, .background .image {
                        background: inherit;
                      }
            - type: weather-forecast
              entity: weather.home
            - type: custom:sun-card
              darkMode: true
              card_mod:
                style: |
                  .sun-card-header .sun-card-text-container:first-child {
                    align-items: flex-start;
                  }
                  .sun-card-header .sun-card-text-container:last-child {
                    align-items: flex-end;
                  }
                  .sun-card-header .sun-card-text-container:last-child .sun-card-text-time {
                    display: flex;
                    flex-direction: row-reverse;
                    align-items: baseline;
                  }
                  .sun-card-header .sun-card-text-container:last-child .sun-card-text-time-period {
                    margin-right: 8px;
                  }
            - type: sensor
              entity: sensor.rodgau_nieder_roden_to_westend_frankfurt_a_m
              name: S1 â†’ Westend
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              entities:
                - type: custom:multiple-entity-row
                  entity: sensor.tankerkoenig_car_tank_24_e5
                  show_state: false
                  name: Neumann Tankstelle
                  secondary_info: last-changed
                  entities:
                    - entity: sensor.tankerkoenig_car_tank_24_e5
                      name: Gas
                    - entity: sensor.tankerkoenig_car_tank_24_diesel
                      name: Diesel
                - type: custom:multiple-entity-row
                  entity: sensor.tankerkoenig_car_tank_24_e5
                  show_state: false
                  name: Tankcenter Rodgau
                  secondary_info: last-changed
                  entities:
                    - entity: sensor.tankerkoenig_tankcenter_rodgau_e5
                      name: Gas
                    - entity: sensor.tankerkoenig_tankcenter_rodgau_diesel
                      name: Diesel
        - type: vertical-stack
          cards:
            # hallway
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Hallway
                icon: mdi:door
                state_color: false
                show_header_toggle: false
              entities:
                - type: custom:multiple-entity-row
                  entity: binary_sensor.hallway_entrance_door_lumi_contact
                  name: Door
                  icon: mdi:door
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: binary_sensor.hallway_entrance_door_lumi_contact
                      name: State
                    - entity: sensor.hallway_entrance_door_lumi_power
                      name: Battery
                - type: custom:text-divider-row
                  entity: sensor.time
                  text: Modes
                  card_mod:
                    style: |
                      h2.text-divider {
                        margin: 0;
                        font-weight: normal;
                        letter-spacing: 0.5px;
                        opacity: .5;
                      }

                      h2.text-divider span {
                        padding: 10px 1em;
                      }
                - entity: switch.vacation_mode
                  secondary_info: last-changed

            # living room
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Living Room
                icon: mdi:sofa
                state_color: true
                show_header_toggle: true
              entities:
                - type: custom:multiple-entity-row
                  entity: sensor.living_room_climate_lumi_temperature
                  name: Climate
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: sensor.living_room_climate_lumi_temperature
                      name: Temperature
                    - entity: sensor.living_room_climate_lumi_humidity
                      name: Humidity
                    - entity: sensor.living_room_climate_lumi_power
                      name: Battery
                - type: custom:text-divider-row
                  entity: sensor.time
                  text: Lights
                  card_mod:
                    style: |
                      h2.text-divider {
                        margin: 0;
                        font-weight: normal;
                        letter-spacing: 0.5px;
                        opacity: .5;
                      }

                      h2.text-divider span {
                        padding: 10px 1em;
                      }
                - type: custom:multiple-entity-row
                  entity: switch.lampe
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.lampe_power
                      name: false
                - type: custom:multiple-entity-row
                  entity: switch.duftlampe
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.duftlampe_power
                      name: false
                - type: custom:multiple-entity-row
                  entity: switch.baum
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.baum_power
                      name: false
                - entity: light.living_room_tv_leds
                  secondary_info: last-changed
                - type: custom:rgb-light-card
                  entity: light.living_room_tv_leds
                  justify: around
                  colors:
                    - color_temp: 360
                      brightness_pct: 5
                    - color_temp: 360
                      brightness_pct: 75
                    - hs_color: [90, 0]
                    - hs_color: [280, 27]
                    - hs_color: [165, 100]
                    - hs_color: [15, 100]

            # kitchen
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Kitchen
                icon: mdi:pot-steam
                state_color: true
                show_header_toggle: true
              entities:
                - type: custom:multiple-entity-row
                  entity: binary_sensor.kitchen_balcony_door_lumi_contact
                  name: Balcony Door
                  icon: mdi:door
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: binary_sensor.kitchen_balcony_door_lumi_contact
                      name: State
                    - entity: sensor.kitchen_balcony_door_lumi_power
                      name: Battery
                - type: custom:multiple-entity-row
                  entity: sensor.kitchen_climate_lumi_temperature
                  name: Climate
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: sensor.kitchen_climate_lumi_temperature
                      name: Temperature
                    - entity: sensor.kitchen_climate_lumi_humidity
                      name: Humidity
                    - entity: sensor.kitchen_climate_lumi_power
                      name: Battery
                - type: custom:text-divider-row
                  entity: sensor.time
                  text: Lights
                  card_mod:
                    style: |
                      h2.text-divider {
                        margin: 0;
                        font-weight: normal;
                        letter-spacing: 0.5px;
                        opacity: .5;
                      }

                      h2.text-divider span {
                        padding: 10px 1em;
                      }
                - type: custom:multiple-entity-row
                  entity: switch.lichterkette
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.lichterkette_power
                      name: false
        - type: vertical-stack
          cards:
            # bedroom
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Bedroom
                icon: mdi:bed
                state_color: true
                show_header_toggle: true
              entities:
                - type: custom:multiple-entity-row
                  entity: sensor.bedroom_climate_lumi_temperature
                  name: Climate
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: sensor.bedroom_climate_lumi_temperature
                      name: Temperature
                    - entity: sensor.bedroom_climate_lumi_humidity
                      name: Humidity
                    - entity: sensor.bedroom_climate_lumi_power
                      name: Battery
                - type: custom:text-divider-row
                  entity: sensor.time
                  text: Lights
                  card_mod:
                    style: |
                      h2.text-divider {
                        margin: 0;
                        font-weight: normal;
                        letter-spacing: 0.5px;
                        opacity: .5;
                      }

                      h2.text-divider span {
                        padding: 10px 1em;
                      }
                - entity: light.bedroom_closet
                  secondary_info: last-changed
                - type: custom:rgb-light-card
                  entity: light.bedroom_closet
                  justify: around
                  colors:
                    - hs_color: [45, 100]
                    - hs_color: [165, 100]
                    - hs_color: [90, 0]
                    - hs_color: [280, 27]
                    - hs_color: [301, 24]
                    - hs_color: [15, 100]

            # childrens room
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Childrens Room
                icon: mdi:baby-face
                state_color: true
                show_header_toggle: true
              entities:
                - type: custom:multiple-entity-row
                  entity: sensor.childrens_room_climate_lumi_temperature
                  name: Climate
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: sensor.childrens_room_climate_lumi_temperature
                      name: Temperature
                    - entity: sensor.childrens_room_climate_lumi_humidity
                      name: Humidity
                    - entity: sensor.childrens_room_climate_lumi_power
                      name: Battery
                - type: custom:text-divider-row
                  entity: sensor.time
                  text: Lights
                  card_mod:
                    style: |
                      h2.text-divider {
                        margin: 0;
                        font-weight: normal;
                        letter-spacing: 0.5px;
                        opacity: .5;
                      }

                      h2.text-divider span {
                        padding: 10px 1em;
                      }
                - entity: switch.love
                  secondary_info: last-changed
                - type: custom:multiple-entity-row
                  entity: switch.kugel
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.kugel_power
                      name: false

            # bathroom
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Bathroom
                icon: mdi:shower
                state_color: true
                show_header_toggle: true
              entities:
                - type: custom:multiple-entity-row
                  entity: sensor.bathroom_climate_lumi_temperature
                  name: Climate
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: sensor.bathroom_climate_lumi_temperature
                      name: Temperature
                    - entity: sensor.bathroom_climate_lumi_humidity
                      name: Humidity
                    - entity: sensor.bathroom_climate_lumi_power
                      name: Battery

            # guest bathroom
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Guest Bathroom
                icon: mdi:shower
                state_color: false
                show_header_toggle: false
              entities:
                - type: custom:multiple-entity-row
                  entity: binary_sensor.guest_bathroom_window_lumi_contact
                  name: Window
                  icon: mdi:window-closed
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: binary_sensor.guest_bathroom_window_lumi_contact
                      name: State
                    - entity: sensor.guest_bathroom_window_lumi_power
                      name: Battery
    card_mod:
      style: |
        ha-card {
          max-width: calc(100% + 7px);
          margin-top: -8px;
          margin-right: -8px;
          margin-left: -7px;
          transition: none;
        }
