title: Bedroom
path: bedroom
icon: mdi:bed
theme: Google - Dark
panel: true
badges: []
cards:
  - type: custom:mod-card
    card:
      type: custom:layout-card
      layout_type: custom:horizontal-layout
      layout:
        max_width: 1000
      cards:
        - type: vertical-stack
          cards:
            - type: entities
              title: Climate
              state_color: false
              show_header_toggle: false
              entities:
                - entity: sensor.bed_room_lumi_temperature
                  secondary_info: last-changed
                  name: Temperature
                - entity: sensor.bed_room_lumi_humidity
                  secondary_info: last-changed
                  name: Humidity
                - entity: sensor.bed_room_lumi_pressure
                  secondary_info: last-changed
                  name: Pressure
                - entity: sensor.bed_room_lumi_power
                  secondary_info: last-changed
                  name: Battery
              footer:
                type: graph
                entity: sensor.bed_room_lumi_temperature
                hours_to_show: 48
        - type: vertical-stack
          cards:
            - type: entities
              title: Lights
              state_color: true
              show_header_toggle: true
              entities:
                - entity: light.bedroom_closet
                  secondary_info: last-changed
                - type: custom:rgb-light-card
                  entity: light.bedroom_closet
                  justify: around
                  colors:
                    - hs_color: [45, 100]
                    - hs_color: [165, 100]
                    - hs_color: [90, 0]
                    - hs_color: [280, 27]
                    - hs_color: [301, 24]
                    - hs_color: [15, 100]
    card_mod:
      style: |
        ha-card {
          max-width: calc(100% + 7px);
          margin-top: -8px;
          margin-right: -8px;
          margin-left: -7px;
          transition: none;
        }
