title: Living Room
path: living-room
icon: mdi:sofa
theme: Google - Dark
panel: true
badges: []
cards:
  - type: custom:mod-card
    card:
      type: custom:layout-card
      layout_type: custom:horizontal-layout
      layout:
        max_width: 1000
      cards:
        - type: vertical-stack
          cards:
            - type: entities
              title: Climate
              state_color: false
              show_header_toggle: false
              entities:
                - entity: sensor.living_room_climate_lumi_temperature
                  secondary_info: last-changed
                  name: Temperature
                - entity: sensor.living_room_climate_lumi_humidity
                  secondary_info: last-changed
                  name: Humidity
                - entity: sensor.living_room_climate_lumi_pressure
                  secondary_info: last-changed
                  name: Pressure
                - entity: sensor.living_room_climate_lumi_power
                  secondary_info: last-changed
                  name: Battery
              footer:
                type: graph
                entity: sensor.living_room_climate_lumi_temperature
                hours_to_show: 48
        - type: vertical-stack
          cards:
            - type: entities
              title: Lights
              state_color: true
              show_header_toggle: true
              entities:
                - type: custom:multiple-entity-row
                  entity: switch.lampe
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.lampe_power
                      name: false
                - type: custom:multiple-entity-row
                  entity: switch.duftlampe
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.duftlampe_power
                      name: false
                - type: custom:multiple-entity-row
                  entity: switch.baum
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.baum_power
                      name: false
                - entity: light.living_room_tv_leds
                  secondary_info: last-changed
                - type: custom:rgb-light-card
                  entity: light.living_room_tv_leds
                  justify: around
                  colors:
                    - color_temp: 360
                      brightness_pct: 5
                    - color_temp: 360
                      brightness_pct: 75
                    - hs_color: [90, 0]
                    - hs_color: [280, 27]
                    - hs_color: [165, 100]
                    - hs_color: [15, 100]
    card_mod:
      style: |
        ha-card {
          max-width: calc(100% + 7px);
          margin-top: -8px;
          margin-right: -8px;
          margin-left: -7px;
          transition: none;
        }
