title: Tech
path: tech
icon: mdi:server-network
theme: Google - Dark
panel: true
badges: []
cards:
  - type: custom:mod-card
    card:
      type: custom:layout-card
      layout_type: custom:horizontal-layout
      layout:
        max_width: 1000
      cards:
        - type: vertical-stack
          cards:
            - type: horizontal-stack
              cards:
                - type: sensor
                  name: Public IP
                  graph: none
                  icon: mdi:web
                  entity: sensor.fritz_box_public_ip
                - type: sensor
                  name: Last Boot
                  graph: none
                  icon: mdi:clock-outline
                  entity: sensor.relative_last_boot
            - type: horizontal-stack
              cards:
                - type: sensor
                  name: Downstream
                  graph: none
                  icon: mdi:arrow-down
                  entity: sensor.fritz_box_downstream_percentage
                - type: sensor
                  name: Upstream
                  graph: none
                  icon: mdi:arrow-up
                  entity: sensor.fritz_box_upstream_percentage
                - type: sensor
                  name: Uptime
                  graph: none
                  icon: mdi:clock-outline
                  entity: sensor.fritz_box_connection_uptime
            - type: entities
              title: Tailscale
              entities:
                - type: custom:multiple-entity-row
                  entity: sensor.coruscant_last_seen
                  name: Coruscant
                  icon: mdi:server
                  state_header: Last Seen
                  format: total
                  secondary_info:
                    entity: sensor.coruscant_ip_address
                    name: false
                  entities:
                    - entity: binary_sensor.coruscant_client
                      name: false
                      hide_unavailable: true
                      hide_if: 'off'
                - type: custom:multiple-entity-row
                  entity: sensor.jakku_last_seen
                  name: Jakku
                  icon: mdi:server
                  state_header: Last Seen
                  format: total
                  secondary_info:
                    entity: sensor.jakku_ip_address
                    name: false
                  entities:
                    - entity: binary_sensor.jakku_client
                      name: false
                      hide_unavailable: true
                      hide_if: 'off'
                - type: custom:multiple-entity-row
                  entity: sensor.ryloth_last_seen
                  name: Ryloth
                  icon: mdi:server
                  state_header: Last Seen
                  format: total
                  secondary_info:
                    entity: sensor.ryloth_ip_address
                    name: false
                  entities:
                    - entity: binary_sensor.ryloth_client
                      name: false
                      hide_unavailable: true
                      hide_if: 'off'
                - type: custom:multiple-entity-row
                  entity: sensor.ilum_last_seen
                  name: Ilum
                  icon: mdi:server
                  state_header: Last Seen
                  format: total
                  secondary_info:
                    entity: sensor.ilum_ip_address
                    name: false
                  entities:
                    - entity: binary_sensor.ilum_client
                      name: false
                      hide_unavailable: true
                      hide_if: 'off'
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                title: Synology NAS
                show_header_toggle: false
              entities:
                - entity: switch.synology_nas
                  name: Status
                - entity: binary_sensor.synologynas_security_status
                  name: Security Status
                - type: custom:multiple-entity-row
                  entity: sensor.synologynas_cpu_load_average_1_min
                  name: CPU load average
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: sensor.synologynas_cpu_load_average_1_min
                      name: 1m
                    - entity: sensor.synologynas_cpu_load_average_5_min
                      name: 5m
                    - entity: sensor.synologynas_cpu_load_average_15_min
                      name: 15m
                - type: custom:multiple-entity-row
                  entity: sensor.synologynas_drive_1_status
                  name: Drive status
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: sensor.synologynas_drive_1_status
                      name: Drive 1
                    - entity: sensor.synologynas_drive_1_status_2
                      name: Drive 2
                    - entity: sensor.synologynas_drive_2_status
                      name: Drive 3
                    - entity: sensor.synologynas_drive_2_status_2
                      name: Drive 4
                - type: custom:multiple-entity-row
                  entity: sensor.synologynas_drive_1_temperature
                  name: Drive temperature
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: sensor.synologynas_drive_1_temperature
                      name: Drive 1
                    - entity: sensor.synologynas_drive_1_temperature_2
                      name: Drive 2
                    - entity: sensor.synologynas_drive_2_temperature
                      name: Drive 3
                    - entity: sensor.synologynas_drive_2_temperature_2
                      name: Drive 4
                - type: custom:multiple-entity-row
                  entity: sensor.synologynas_volume_1_status
                  name: Volume
                  icon: mdi:harddisk
                  secondary_info: last-changed
                  show_state: false
                  entities:
                    - entity: sensor.synologynas_volume_1_status
                      name: Status
                    - entity: sensor.synologynas_volume_1_used_space
                      name: Used
                    - entity: sensor.synologynas_volume_1_volume_used
                      name: Percent
        - type: vertical-stack
          cards:
            - type: entity-filter
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                type: entities
                title: GitHub
                show_header_toggle: false
              entities:
                - type: custom:multiple-entity-row
                  entity: sensor.pascaliske_infrastructure_stars
                  name: pascaliske/infrastructure
                  state_header: Stars
                  unit: false
                  icon: mdi:github
                  secondary_info:
                    entity: sensor.pascaliske_infrastructure_latest_commit
                    name: false
                  tap_action:
                    action: url
                    url_path: https://github.com/pascaliske/infrastructure
                  entities:
                    - entity: sensor.pascaliske_infrastructure_issues
                      name: Issues
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/infrastructure/issues
                    - entity: sensor.pascaliske_infrastructure_pull_requests
                      name: PRs
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/infrastructure/pulls
                - type: custom:multiple-entity-row
                  entity: sensor.pascaliske_helm_charts_stars
                  name: pascaliske/helm-charts
                  state_header: Stars
                  unit: false
                  icon: mdi:github
                  secondary_info:
                    entity: sensor.pascaliske_helm_charts_latest_commit
                    name: false
                  tap_action:
                    action: url
                    url_path: https://github.com/pascaliske/helm-charts
                  entities:
                    - entity: sensor.pascaliske_helm_charts_issues
                      name: Issues
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/helm-charts/issues
                    - entity: sensor.pascaliske_helm_charts_pull_requests
                      name: PRs
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/helm-charts/pulls
                - type: custom:multiple-entity-row
                  entity: sensor.pascaliske_docker_alpine_curl_jq_stars
                  name: pascaliske/docker-alpine-curl-jq
                  state_header: Stars
                  unit: false
                  icon: mdi:github
                  secondary_info:
                    entity: sensor.pascaliske_docker_alpine_curl_jq_latest_commit
                    name: false
                  tap_action:
                    action: url
                    url_path: https://github.com/pascaliske/docker-alpine-curl-jq
                  entities:
                    - entity: sensor.pascaliske_docker_alpine_curl_jq_issues
                      name: Issues
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/docker-alpine-curl-jq/issues
                    - entity: sensor.pascaliske_docker_alpine_curl_jq_pull_requests
                      name: PRs
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/docker-alpine-curl-jq/pulls
                - type: custom:multiple-entity-row
                  entity: sensor.pascaliske_docker_autorestic_stars
                  name: pascaliske/docker-autorestic
                  state_header: Stars
                  unit: false
                  icon: mdi:github
                  secondary_info:
                    entity: sensor.pascaliske_docker_autorestic_latest_commit
                    name: false
                  tap_action:
                    action: url
                    url_path: https://github.com/pascaliske/docker-autorestic
                  entities:
                    - entity: sensor.pascaliske_docker_autorestic_issues
                      name: Issues
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/docker-autorestic/issues
                    - entity: sensor.pascaliske_docker_autorestic_pull_requests
                      name: PRs
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/docker-autorestic/pulls
                - type: custom:multiple-entity-row
                  entity: sensor.pascaliske_docker_traefik_errors_stars
                  name: pascaliske/docker-traefik-errors
                  state_header: Stars
                  unit: false
                  icon: mdi:github
                  secondary_info:
                    entity: sensor.pascaliske_docker_traefik_errors_latest_commit
                    name: false
                  tap_action:
                    action: url
                    url_path: https://github.com/pascaliske/docker-traefik-errors
                  entities:
                    - entity: sensor.pascaliske_docker_traefik_errors_issues
                      name: Issues
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/docker-traefik-errors/issues
                    - entity: sensor.pascaliske_docker_traefik_errors_pull_requests
                      name: PRs
                      unit: false
                      tap_action:
                        action: url
                        url_path: https://github.com/pascaliske/docker-traefik-errors/pulls
            - type: entity-filter
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                type: entities
                title: GitLab
                show_header_toggle: false
              entities:
                - entity: sensor.time
                  type: button
                  name: Admin Dashboard
                  icon: mdi:cog
                  action_name: Open
                  tap_action:
                    action: url
                    url_path: !secret gitlab_admin_url
            - type: entities
              title: Pipelines
              show_header_toggle: false
              entities:
                - entity: sensor.jh_of_app
                  name: pi-webdesign/jh-of/app
                  tap_action:
                    action: url
                    url_path: https://git.pascaliske.dev/pi-webdesign/jh-of/app
                - entity: sensor.jh_of_api
                  name: pi-webdesign/jh-of/api
                  tap_action:
                    action: url
                    url_path: https://git.pascaliske.dev/pi-webdesign/jh-of/api
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                type: entities
                title: Epson ET-2750
                icon: mdi:printer
                show_header_toggle: false
                entities: []
              entities:
                - entity: sensor.epson_et_2750_series
                - entity: sensor.epson_et_2750_series_black_ink
                - entity: sensor.epson_et_2750_series_cyan_ink
                - entity: sensor.epson_et_2750_series_magenta_ink
                - entity: sensor.epson_et_2750_series_yellow_ink
            - type: entity-filter
              show_empty: false
              state_filter:
                - operator: '!='
                  value: 'unavailable'
              card:
                type: entities
                title: Canon MX-470
                icon: mdi:printer
                show_header_toggle: false
                entities: []
              entities:
                - entity: sensor.canon_mx470_series
                - entity: sensor.canon_mx470_series_black
                - entity: sensor.canon_mx470_series_color
        - type: vertical-stack
          cards:
            - type: entities
              title: Home Assistant
              show_header_toggle: false
              entities:
                - entity: binary_sensor.remote_ui
                  secondary_info: last-changed
                - type: custom:multiple-entity-row
                  entity: sensor.latest_version
                  name: Versions
                  state_header: Latest
                  secondary_info: last-changed
                  entities:
                    - entity: sensor.current_version
                      name: Current
            - type: entities
              title: Wake Devices
              show_header_toggle: false
              entities:
                - type: button
                  name: Synology NAS
                  action_name: Wake
                  show_state: false
                  tap_action:
                    action: call-service
                    service: wake_on_lan.send_magic_packet
                    service_data:
                      mac: !secret mac_synology_nas
                - type: button
                  name: FFMMBP-207
                  action_name: Wake
                  show_state: false
                  tap_action:
                    action: call-service
                    service: wake_on_lan.send_magic_packet
                    service_data:
                      mac: !secret mac_ffmmbp207
                - type: button
                  name: PS4-PI
                  action_name: Wake
                  show_state: false
                  tap_action:
                    action: call-service
                    service: media_player.turn_on
                    service_data:
                      entity_id: media_player.ps4_pi
    card_mod:
      style: |
        ha-card {
          max-width: calc(100% + 7px);
          margin-top: -8px;
          margin-right: -8px;
          margin-left: -7px;
          transition: none;
        }
