ports:
  dns: 53
  http: 4000

log:
  level: info
  format: text

upstreams:
  init:
    strategy: fast
  groups:
    default:
      - tcp-tls:cloudflared-dns.cloudflared.svc.cluster.local:5053
      - tcp-tls:unbound-dns.unbound.svc.cluster.local:5053
      - https://1.1.1.1/dns-query
  strategy: strict
  timeout: 3s

customDNS:
  mapping:
    # general
    iske.cloud: ${IP_SERVICE_VIP}

    # cluster
    cluster.iske.cloud: ${IP_CLUSTER_VIP}

    # legacy cluster
    coruscant.iske.cloud: ${IP_CORUSCANT}
    kashyyyk.iske.cloud: ${IP_KASHYYYK}
    dathomir.iske.cloud: ${IP_DATHOMIR}
    jakku.iske.cloud: ${IP_JAKKU}

    # servers
    ryloth.iske.cloud: ${IP_RYLOTH}
    ilum.iske.cloud: ${IP_ILUM}
    zigbeeproxy.iske.cloud: ${IP_ZIGBEEPROXY}

    # simplified unifi layer 2 device adoption
    unifi: ${IP_SERVICE_VIP}

conditional:
  mapping:
    fritz.box: ${IP_ROUTER}

clientLookup:
  upstream: ${IP_ROUTER}
  singleNameOrder:
    - 2
    - 1

blocking:
  denylists:
    all:
      # - https://blocklistproject.github.io/Lists/ads.txt
      # - https://blocklistproject.github.io/Lists/drugs.txt
      # - https://blocklistproject.github.io/Lists/fraud.txt
      # - https://blocklistproject.github.io/Lists/malware.txt
      # - https://blocklistproject.github.io/Lists/phishing.txt
      # - https://blocklistproject.github.io/Lists/porn.txt
      # - https://blocklistproject.github.io/Lists/scam.txt
      # - https://blocklistproject.github.io/Lists/tiktok.txt
      # - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      # - https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
      - https://raw.githubusercontent.com/pascaliske/infrastructure/main/cluster/services/blocky/blocklist.txt
  allowlists:
    all:
      - https://raw.githubusercontent.com/pascaliske/infrastructure/main/cluster/services/blocky/allowlist.txt
  clientGroupsBlock:
    default:
      - all
  loading:
    refreshPeriod: 8h
    strategy: fast
    concurrency: 2

caching:
  minTime: 5m
  maxTime: 20m
  prefetching: true

redis:
  address: mymaster
  sentinelAddresses:
    - rfs-redis:26379

prometheus:
  enable: true

queryLog:
  type: none
