name: Auto Merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Config Check
      - Linting

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          PRESET: DEPENDABOT_MINOR
          MERGE_METHOD: MERGE
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
