---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia
  - cert-manager
  - cloudflare-operator
  - cnpg-system
  - crowdsec
  - flux-system
  - kube-system
  - local-path-storage
  - metallb
  - monitoring
  - redis-operator
  - silence-operator
  - tailscale-operator
  - traefik
  - traefik-errors
  - trivy-operator
  - uptime-kuma
  - velero
