---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia
  - cert-manager
  - cloudnative-pg
  - flux-system
  - kube-system
  - kured
  - local-path-storage
  - metallb
  - monitoring
  - redis-operator
  - silence-operator
  - traefik
  - traefik-errors
  - trivy-operator
  - velero
